Task/tec00/gerald devhttps://github.com/Luminescence-inc/Project-Delta-Frontend/pull/109
Luminescence-inc/Project-Delta-Frontend pull request #111
Opened 2024-07-26 07:08 UTC by geraldkachi

fix conflict

2024-07-26 12:29 UTC, Benrobo commented on src/components/MultiSearch.tsx
> +      <label className="text-sm font-normal font-inter leading-[19px] text-[#0E2D52]">
Please, colors shouldn't be hardcoded. based on the color type, check the `tailwind.config.ts` file and look for similar color name and add that there then reference the color using tailwind classes

2024-07-26 12:29 UTC, Benrobo commented on src/app/page.tsx
> +          <h1 className="w-full text-[25px] font-bold leading-[38px] tracking-normal text-left text-[##0E2D52] font-pp">
Same with this

2024-07-26 12:33 UTC, Benrobo requested changes
Good job @geraldkachi , but please go through the reviews and make necessary adjustments.

Also please update your pull requests title to easier readability. It should reference the ticket you're working on jira with a short description: `task/TEC-[number]/<short-description>`

2024-07-26 12:33 UTC, Benrobo commented on src/components/ui/button.tsx
> +            <span>{leftIcon && leftIcon}</span>
Same here

2024-07-26 12:34 UTC, Benrobo commented on src/components/ui/button.tsx
> +            <span>{rightIcon && rightIcon}</span>
same here

2024-07-26 12:34 UTC, Benrobo commented on src/components/ui/button.tsx
> +        <span>{children}</span>
Same here

2024-07-28 22:07 UTC, geraldkachi commented on src/components/ui/button.tsx
> +        <span>{children}</span>
okay removed

2024-07-28 22:07 UTC, geraldkachi commented on src/components/ui/button.tsx
> +            <span>{leftIcon && leftIcon}</span>
okay boss

2024-07-28 22:08 UTC, geraldkachi commented on src/components/ui/button.tsx
> +            <span>{leftIcon && leftIcon}</span>
okay

2024-07-28 22:09 UTC, geraldkachi commented on src/components/MultiSearch.tsx
> +      <label className="text-sm font-normal font-inter leading-[19px] text-[#0E2D52]">
hmm okay corrected accordingly

2024-07-28 22:10 UTC, geraldkachi commented on src/app/page.tsx
> +          <h1 className="w-full text-[25px] font-bold leading-[38px] tracking-normal text-left text-[##0E2D52] font-pp">
okay boss

2024-07-28 22:15 UTC, geraldkachi commented on src/components/ui/button.tsx
> +            <span>{leftIcon && leftIcon}</span>
the span is an inline tag and it works for the alignment of the icon that's why i put it there.

it slike have three different items in one tag. with the inline it contains it

2024-07-29 11:25 UTC, osxar approved these changes

2024-07-29 11:26 UTC, osxar approved these changes
Code Review Changes has been implemented

2024-07-29 11:26 UTC, merged