Task/tec180/business onboarding
Luminescence-inc/Project-Delta-Frontend pull request #122
Opened 2024-07-31 05:48 UTC by geraldkachi

still on onboarding pixel perfecting 
and correction on the tire app

2024-08-06 15:04 UTC, Benrobo commented on src/app/loading.tsx
> +import React from 'react'
There is no need for this, before attempting to create any component please check if a component of that type exists first, if it does, you could try optimizing it rather than creating new one.

2024-08-06 15:06 UTC, Benrobo commented on src/app/styles/global.css
please revert  this back.. No local font is used for a reason, `font.ts` contains our application fonts needed and directly imported from google to optimize page load time.

2024-08-06 15:10 UTC, Benrobo commented on src/components/icons/index.tsx
>      <path d="M19.5 11H13.5V5C13.5 4.73478 13.3946 4.48043 13.2071 4.29289C13.0196 4.10536 12.7652 4 12.5 4C12.2348 4 11.9804 4.10536 11.7929 4.29289C11.6054 4.48043 11.5 4.73478 11.5 5V11H5.5C5.23478
this icons doesn't seem to be from `Lucide`, also, every icons were made to be customizable in case it were to be used within other sections of the app with different size and colors, so avoid specifying the `fill` attributes. If it a custom icon used in one place, just add it within the `public/assets/icons` directory.

2024-08-06 15:12 UTC, Benrobo commented on src/components/ui/input.tsx
> -        <label className="text-[14px] font-medium font-pp text-dark-100/60">
Please add the `font-pp` classname back, without that the poppins font variant wont take effect.

2024-08-06 15:14 UTC, Benrobo commented on src/modules/register-business/components/OperationInfo.tsx
> +  // what is expected to use
avoid making unnecessary comments within the app, if it no longer in-use, just get rid of them, if you plan on coming back to that comment, please document it properly for the next developer so they know exactly why that was commented out.

2024-08-06 15:15 UTC, Benrobo commented on src/modules/search/components/LayoutCard.tsx
> +  const pathname = usePathname()
This specific component was made to be `SSR` and not client side rendered, as a result, we make sure no client specific API or hooks was passed directly to this component. please revert it back, a meeting would be held concerning this.

2024-08-06 15:17 UTC, Benrobo requested changes
@geraldkachi i've done some minor reviews on this, i believe a more detailed one would be done within the meeting.

2024-08-07 09:05 UTC, geraldkachi commented on src/app/layout.tsx
> -        className={cn(inter.variable, poppins.variable, open_sans.variable)}
Okay boss. it was a task assign to me

2024-08-07 09:07 UTC, geraldkachi commented on src/app/loading.tsx
> +import React from 'react'
alright noted i have removed it 
its a global 
default loading for next.

2024-08-07 09:07 UTC, geraldkachi commented on src/app/styles/global.css
alright noted reverted

2024-08-07 09:44 UTC, geraldkachi commented on src/components/icons/index.tsx
>      <path d="M19.5 11H13.5V5C13.5 4.73478 13.3946 4.48043 13.2071 4.29289C13.0196 4.10536 12.7652 4 12.5 4C12.2348 4 11.9804 4.10536 11.7929 4.29289C11.6054 4.48043 11.5 4.73478 11.5 5V11H5.5C5.23478
this i do not understand. you took these icon from figm 
i removed the svg and just left the path
just as you told me

what is lucide ?

2024-08-07 09:44 UTC, geraldkachi commented on src/components/ui/input.tsx
> -        <label className="text-[14px] font-medium font-pp text-dark-100/60">
okay

2024-08-07 09:51 UTC, geraldkachi commented on src/modules/search/components/LayoutCard.tsx
> +  const pathname = usePathname()
ah omo

2024-08-07 09:54 UTC, geraldkachi commented on src/modules/search/components/LayoutCard.tsx
> +  const pathname = usePathname()
Okay

2024-08-07 10:03 UTC, geraldkachi commented on src/modules/search/components/LayoutCard.tsx
> +  const pathname = usePathname()
this is going to be a problem 
the card i modified it in another task 
then i checkout off that branch

2024-08-09 13:47 UTC, osxar approved these changes

2024-08-09 13:47 UTC, merged