fix: updated businesses card image to include
Luminescence-inc/Project-Delta-Frontend pull request #140
Opened 2024-08-20 15:10 UTC by Benrobo

updated business listing, business profile page to use cropped img if available otherwise switch to default

2024-08-21 04:09 UTC, osxar requested changes
When I create a new business with a cropped logo, the business fails to save.

2024-08-21 04:09 UTC, osxar commented on src/app/biz/[loc]/[business_id]/page.tsx
> +              src={constructBizImgUrl(businessDetails?.croppedImageUrl!)}
@Benrobo given that the croppedImageUrl is a new feature, our currently registered businesses on both dev and prod, doesn't have the url. Please setup a check that does: 1) check for the croppedUrl, if it doesn't exists, then it checks the originalUrl, if that doesn't exists, then it renders the default business logo

2024-08-21 04:09 UTC, osxar commented on src/utils/index.ts
> +    ? "https://res.cloudinary.com/drwt2qqf9/image/upload/v1721488956/default-img_vhxk4d.jpg"
@Benrobo why don't we set this up as a variable in a config file

2024-08-21 04:12 UTC, osxar commented
@Benrobo Also the default image looks stretched. Please use the new one on figma, thanks.
<img width="291" alt="Screenshot 2024-08-21 at 12 11 38 AM" src="https://github.com/user-attachments/assets/e1e19f43-7da2-470d-a642-8a08521a4a51">

2024-08-21 09:36 UTC, Benrobo commented on src/app/biz/[loc]/[business_id]/page.tsx
> +              src={constructBizImgUrl(businessDetails?.croppedImageUrl!)}
concerning this, the image displayed on the business card should be the cropped version of that image. When the image doesn't exists or when the user doesn;t upload one, that value becomes null, which automatically get assigned to the default image in cloudinary.

2024-08-22 03:58 UTC, osxar commented on src/app/biz/[loc]/[business_id]/page.tsx
> +              src={constructBizImgUrl(businessDetails?.croppedImageUrl!)}
yhea, i get that, but if we deploy this change as it is, all the business profile that we currently have will show the default business image, and we don't want that. We will have to send an email to each users telling them of the upgrade we have done to the application and requesting them to crop their image the way they would like it. When that is done, we can then revert to this implementation.

2024-08-22 04:03 UTC, osxar commented
@Benrobo I also noticed that these pages are still using the originalUrl instead of the cropped url:

1) Similar businesses on business details page
2) My business listing page (where a business owner goes to checkout a list of his/her businesses)

2024-08-22 19:59 UTC, osxar approved these changes

2024-08-22 19:59 UTC, merged