Origin/task/tec194/business update
Luminescence-inc/Project-Delta-Frontend pull request #146
Opened 2024-08-26 20:17 UTC by geraldkachi

2024-08-27 11:31 UTC, Benrobo requested changes
Also, this page currently had some well optimized updates so the changes you've added here won't reflect on dev, later on once we're done migrating all your UI changes, you would need to pull from dev to have a clean branch.

2024-08-27 11:31 UTC, Benrobo commented on src/app/register-business/page.tsx
> +  const [activeTabN, setActiveTabN] = useState(0);
any reason behind creating similar states with same functionalities?

2024-08-27 11:31 UTC, Benrobo commented on src/app/register-business/page.tsx
> +
Add this function within `utils/index.ts` file.

2024-08-27 11:31 UTC, Benrobo commented on src/app/register-business/page.tsx
> +      {/* {(isDesktop && isUpdateMode) ? ( */}
remove redundant comment

2024-08-28 11:04 UTC, geraldkachi commented
Okay

2024-08-29 11:42 UTC, merged